import '../models/models.dart';

class AppConstants {
  static const List<TemplateItem> templates = [
    TemplateItem(
      id: 'watercolor-roses',
      title: 'Watercolor Roses',
      category: 'Floral',
      tradition: 'Soft Floral Watercolor',
      description: 'Hand-painted blush roses with warm serif typography for a graceful remembrance.',
      imageUrl: 'https://images.unsplash.com/photo-1526047932273-341f2a7631f9?q=80&w=800&auto=format&fit=crop',
      dimensions: '8.5" x 11" Bi-fold',
      productType: 'bifold',
      defaultThemeId: 'rose-heritage',
    ),
    TemplateItem(
      id: 'ocean-sunset',
      title: 'Ocean Sunset',
      category: 'Modern',
      tradition: 'Coastal Serenity',
      description: 'Gentle golden horizon waves bringing peace and peaceful reflection.',
      imageUrl: 'https://images.unsplash.com/photo-1518837695005-2083093ee35b?q=80&w=800&auto=format&fit=crop',
      dimensions: '8.5" x 11" Bi-fold',
      productType: 'bifold',
      defaultThemeId: 'ocean-horizon',
    ),
    TemplateItem(
      id: 'victorian-lace',
      title: 'Victorian Lace',
      category: 'Classic',
      tradition: 'Timeless Vintage',
      description: 'Intricate vintage filigree and parchment tones honoring a long, cherished life.',
      imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=800&auto=format&fit=crop',
      dimensions: '8.5" x 11" Bi-fold',
      productType: 'bifold',
      defaultThemeId: 'celestial-gold',
    ),
    TemplateItem(
      id: 'cherry-blossoms',
      title: 'Cherry Blossoms',
      category: 'Floral',
      tradition: 'Botanical Spring',
      description: 'Delicate pink spring blossoms representing the delicate beauty of life.',
      imageUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?q=80&w=800&auto=format&fit=crop',
      dimensions: '8.5" x 11" Bi-fold',
      productType: 'bifold',
      defaultThemeId: 'rose-heritage',
    ),
    TemplateItem(
      id: 'mountain-serenity',
      title: 'Mountain Serenity',
      category: 'Nature',
      tradition: 'Alpine Majesty',
      description: 'Soaring misty peaks and quiet alpine lakes for lovers of the great outdoors.',
      imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=800&auto=format&fit=crop',
      dimensions: '8.5" x 14" Tri-fold',
      productType: 'trifold',
      defaultThemeId: 'serenity-sage',
    ),
    TemplateItem(
      id: 'sacred-cross',
      title: 'Sacred Cross',
      category: 'Religious',
      tradition: 'Christian / Faith',
      description: 'Luminous cross and scripture watermark honoring eternal faith and salvation.',
      imageUrl: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?q=80&w=800&auto=format&fit=crop',
      dimensions: '2.5" x 4.25" Keepsake',
      productType: 'cards',
      defaultThemeId: 'celestial-gold',
    ),
    TemplateItem(
      id: 'autumn-leaves',
      title: 'Autumn Leaves',
      category: 'Nature',
      tradition: 'Seasonal Warmth',
      description: 'Rich amber and golden foliage celebrating a warm and vibrant legacy.',
      imageUrl: 'https://images.unsplash.com/photo-1509114397022-ed747cca3f65?q=80&w=800&auto=format&fit=crop',
      dimensions: '8.5" x 11" Bi-fold',
      productType: 'bifold',
      defaultThemeId: 'celestial-gold',
    ),
    TemplateItem(
      id: 'wisteria-garden',
      title: 'Wisteria Garden',
      category: 'Floral',
      tradition: 'Soft Lavender Garden',
      description: 'Cascading purple blooms and elegant script lettering.',
      imageUrl: 'https://images.unsplash.com/photo-1516528387618-afa90b13e000?q=80&w=800&auto=format&fit=crop',
      dimensions: '5" x 7" Invitation',
      productType: 'invitation',
      defaultThemeId: 'serenity-sage',
    ),
    TemplateItem(
      id: 'serene-cloud-lake',
      title: 'Serene Cloud Lake',
      category: 'Nature',
      tradition: 'Tranquil Waters',
      description: 'Glass-like lake reflecting soft sky, bringing stillness and comfort.',
      imageUrl: 'https://images.unsplash.com/photo-1439853949127-fa647821eba0?q=80&w=800&auto=format&fit=crop',
      dimensions: '8.5" x 11" Bi-fold',
      productType: 'bifold',
      defaultThemeId: 'ocean-horizon',
    ),
    TemplateItem(
      id: 'monochrome-botanical',
      title: 'Monochrome Botanical',
      category: 'Classic',
      tradition: 'Understated Elegance',
      description: 'Subtle charcoal botanical line art and crisp classic typography.',
      imageUrl: 'https://images.unsplash.com/photo-1490750967868-88aa4486c946?q=80&w=800&auto=format&fit=crop',
      dimensions: '4" x 6" Thank You',
      productType: 'thank-you',
      defaultThemeId: 'midnight-elegance',
    ),
    TemplateItem(
      id: 'blue-eucalyptus',
      title: 'Blue Eucalyptus Grace',
      category: 'Floral',
      tradition: 'Botanical Sage',
      description: 'Soothing sage and eucalyptus wreaths framing the sacred portrait.',
      imageUrl: 'https://images.unsplash.com/photo-1515516089376-88db1e26e9c0?q=80&w=800&auto=format&fit=crop',
      dimensions: '8.5" x 11" Bi-fold',
      productType: 'bifold',
      defaultThemeId: 'serenity-sage',
    ),
    TemplateItem(
      id: 'seafoam-serenity',
      title: 'Seafoam Serenity',
      category: 'Modern',
      tradition: 'Gentle Coastal',
      description: 'Soft turquoise ocean mist bringing light and remembrance.',
      imageUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=800&auto=format&fit=crop',
      dimensions: '2.5" x 4.25" Keepsake',
      productType: 'cards',
      defaultThemeId: 'ocean-horizon',
    ),
    TemplateItem(
      id: 'golden-meadow',
      title: 'Golden Meadow Arch',
      category: 'Nature',
      tradition: 'Sunlit Fields',
      description: 'Warm golden sunlight beaming through prairie fields at dusk.',
      imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=800&auto=format&fit=crop',
      dimensions: '18" x 24" Poster',
      productType: 'posters',
      defaultThemeId: 'celestial-gold',
    ),
    TemplateItem(
      id: 'lily-cross',
      title: 'Lily Cross Memorial',
      category: 'Religious',
      tradition: 'Sacred White Lilies',
      description: 'Pure white Easter lilies framing a golden cross of eternal promise.',
      imageUrl: 'https://images.unsplash.com/photo-1438032005730-c779502df39b?q=80&w=800&auto=format&fit=crop',
      dimensions: '2.5" x 4.25" Keepsake',
      productType: 'cards',
      defaultThemeId: 'celestial-gold',
    ),
    TemplateItem(
      id: 'midnight-starlight',
      title: 'Midnight Starlight',
      category: 'Modern',
      tradition: 'Deep Obsidian',
      description: 'Obsidian starlight background with silver accents and clean modern serif.',
      imageUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=800&auto=format&fit=crop',
      dimensions: '24" x 36" Easel Poster',
      productType: 'posters',
      defaultThemeId: 'midnight-elegance',
    ),
    TemplateItem(
      id: 'vintage-bookmark',
      title: 'Heritage Keepsake Bookmark',
      category: 'Classic',
      tradition: 'Laminated Ribbon',
      description: 'Slender keepsake bookmark with favorite poem and life dates.',
      imageUrl: 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?q=80&w=800&auto=format&fit=crop',
      dimensions: '2" x 8" Bookmark',
      productType: 'bookmarks',
      defaultThemeId: 'celestial-gold',
    ),
  ];

  static const List<Map<String, String>> recentObituaries = [
    {
      "name": "Bailey Marie Bryce",
      "dates": "October 31, 1997 – May 3, 2026",
      "birth": "1997",
      "death": "2026",
      "location": "Savannah, Georgia",
      "photo": "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop",
      "theme": "rose-heritage",
    },
    {
      "name": "Michael Watson",
      "dates": "November 8, 1959 – May 5, 2026",
      "birth": "1959",
      "death": "2026",
      "location": "Austin, Texas",
      "photo": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop",
      "theme": "celestial-gold",
    },
    {
      "name": "Dorothy Y. Brady",
      "dates": "August 9, 1957 – May 8, 2026",
      "birth": "1957",
      "death": "2026",
      "location": "Charleston, South Carolina",
      "photo": "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop",
      "theme": "serenity-sage",
    },
    {
      "name": "William (Bill) J Tidswell Jr",
      "dates": "November 24, 1959 – May 6, 2026",
      "birth": "1959",
      "death": "2026",
      "location": "Denver, Colorado",
      "photo": "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop",
      "theme": "ocean-horizon",
    },
    {
      "name": "Tracie Renee Reinert",
      "dates": "December 13, 1971 – April 13, 2026",
      "birth": "1971",
      "death": "2026",
      "location": "Seattle, Washington",
      "photo": "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop",
      "theme": "rose-heritage",
    },
    {
      "name": "Norman E. Dierkes",
      "dates": "July 1, 1949 – May 14, 2026",
      "birth": "1949",
      "death": "2026",
      "location": "Boston, Massachusetts",
      "photo": "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=600&auto=format&fit=crop",
      "theme": "midnight-elegance",
    },
  ];
}
